-- ============================================================
-- Webflow CMS Import — Seed Data for Supabase
-- Generated 2026-03-23
-- ============================================================
-- Run this AFTER migration.sql (schema must exist)
-- This REPLACES the seed data section of migration.sql
-- ============================================================

-- Clear existing blog posts and re-seed
DELETE FROM blog_posts;

INSERT INTO blog_posts (title, url, category, tag, excerpt, date, featured, sort_order) VALUES
  ('Methow Valley and Washington Pass', 'https://irunearth.substack.com/p/methow-valley-and-washington-pass', 'north-america', 'North America', 'Quick Note to readers and my run from Twisp to Marblemount', '2024-05-04', false, 1),
  ('That’s a wrap', 'https://irunearth.substack.com/p/thats-a-wrap', 'north-america', 'North America', 'I completed the big dumb adventure running through Seattle today. unlimited gratitude for everyone who has played a part in this mission big or small.', '2024-05-02', false, 2),
  ('The penultimate push', 'https://irunearth.substack.com/p/the-penultimate-push', 'north-america', 'North America', 'Through Bothell to Kirkland', '2024-05-01', false, 3),
  ('Okanogan Valley', 'https://irunearth.substack.com/p/okanogan-valley', 'north-america', 'North America', '100 miles in three days through America’s apple country', '2024-04-29', false, 4),
  ('Run ski baby jogger adventure finish birthday marathon', 'https://irunearth.substack.com/p/run-ski-baby-jogger-adventure-finish', 'north-america', 'North America', 'May 1 — Seattleites mark down your calendars!', '2024-04-27', false, 5),
  ('Welcome to the USA', 'https://irunearth.substack.com/p/welcome-to-the-usa', 'north-america', 'North America', 'From Christina Lake, British Columbia across the Canada-US border to Republic, Washington', '2024-04-26', false, 6),
  ('Old Rossland-Cascade Highway Ski Traverse', 'https://irunearth.substack.com/p/old-rossland-cascade-highway-ski', 'north-america', 'North America', 'A romp over dirt, mud, sand, slush involving a flat tire, wrong turn, misinformation, and ditching my baby (jogger)', '2024-04-22', false, 7),
  ('Farewell Canada', 'https://irunearth.substack.com/p/farewell-canada', 'north-america', 'North America', 'Goodbye Canada and hello hello again Washington. quick run through the numbers', '2024-04-18', false, 8),
  ('Welcome to Christina Lake', 'https://irunearth.substack.com/p/welcome-to-christina-lake', 'north-america', 'North America', 'Over the old Rossland Cascade Highway', '2024-04-16', false, 9),
  ('How Slocan you go?', 'https://irunearth.substack.com/p/how-slocan-you-go', 'north-america', 'North America', 'Through the Slocan Valley from New Denver to Rossland', '2024-04-14', false, 10),
  ('Lake to Ski to Lake', 'https://irunearth.substack.com/p/lake-to-ski-to-lake', 'north-america', 'North America', 'From Kootenay Lake to Retallak to New Denver on Slocan Lake', '2024-04-11', false, 11),
  ('Gray Creek Pass Ski Traverse', 'https://irunearth.substack.com/p/gray-creek-pass-ski-traverse', 'north-america', 'North America', 'Dirt, mud, slush, rain, and even some patches of powder', '2024-04-08', false, 12),
  ('Kootenay Bay', 'https://irunearth.substack.com/p/kootenay-bay', 'north-america', 'North America', 'Made it over Gray Creek Pass', '2024-04-07', false, 13),
  ('Farewell', 'https://irunearth.substack.com/p/farewell', 'north-america', 'North America', 'A sad goodbye to the adventure and blog', '2024-04-02', false, 14),
  ('Terra Tributa', 'https://irunearth.substack.com/p/terra-tributa', 'north-america', 'North America', 'A day in Kimberley with Vanessa, Bertrand, Léo, and Lucas', '2024-04-01', false, 15),
  ('Kimberley', 'https://irunearth.substack.com/p/kimberley', 'north-america', 'North America', '“A good place to be”', '2024-03-31', false, 16),
  ('Johnson Lake Recreation Site', 'https://irunearth.substack.com/p/johnson-lake-recreation-site', 'north-america', 'North America', 'Hit a wall', '2024-03-30', false, 17),
  ('Kootenay National Park', 'https://irunearth.substack.com/p/kootenay-national-park', 'north-america', 'North America', 'Olly on the run', '2024-03-29', false, 18),
  ('Surprise pass trip report', 'https://irunearth.substack.com/p/surprise-pass', 'north-america', 'North America', 'Orange you glad I didn’t say banana', '2024-03-25', false, 19),
  ('Icefields parkway', 'https://irunearth.substack.com/p/icefields-parkway', 'north-america', 'North America', 'We made it', '2024-03-24', false, 20),
  ('Maligne Canyon', 'https://irunearth.substack.com/p/maligne-canyon', 'north-america', 'North America', 'An ice walk in maligne canyon', '2024-03-16', false, 21),
  ('Jasper', 'https://irunearth.substack.com/p/jasper', 'north-america', 'North America', 'A day in Jasper and overdue physical therapy', '2024-03-15', false, 22),
  ('Berg Lake and Mt Robson Provincial Park', 'https://irunearth.substack.com/p/berg-lake-and-mt-robson-provincial', 'north-america', 'North America', 'A ski tour to Berg Lake and the run to Jasper', '2024-03-14', false, 23),
  ('Day in Valemount', 'https://irunearth.substack.com/p/day-in-valemount', 'north-america', 'North America', 'Another elementary school talk and getting to know my hosts', '2024-03-08', false, 24),
  ('Welcome to Valemount', 'https://irunearth.substack.com/p/welcome-to-valemount', 'north-america', 'North America', 'A snowy 90km run with high highs and low lows', '2024-03-07', false, 25),
  ('Onward', 'https://irunearth.substack.com/p/onward', 'north-america', 'North America', 'The Onslows send me onward', '2024-03-05', false, 26),
  ('Snowmobiling', 'https://irunearth.substack.com/p/snowmobiling', 'north-america', 'North America', 'A window into the world of snow machines', '2024-03-04', false, 27),
  ('Waking up', 'https://irunearth.substack.com/p/waking-up', 'north-america', 'North America', 'Why is it called a wake when you look at a dead person?', '2024-03-03', false, 28),
  ('Fresh perspective with a new coach', 'https://irunearth.substack.com/p/fresh-perspective-with-a-new-coach', 'north-america', 'North America', 'The adventure finally has a coach', '2024-03-02', false, 29),
  ('Sitting on dogs', 'https://irunearth.substack.com/p/sitting-on-dogs', 'north-america', 'North America', 'Catch up on lord of the rings and the news', '2024-03-01', false, 30),
  ('Let it snow', 'https://irunearth.substack.com/p/let-it-snow', 'north-america', 'North America', 'Snow is here and healing is on the horizon', '2024-02-29', false, 31),
  ('Blue River school', 'https://irunearth.substack.com/p/blue-river-school', 'north-america', 'North America', 'Talk at the school and then a whole bunch of nothing', '2024-02-28', false, 32),
  ('Welcome to Blue River', 'https://irunearth.substack.com/p/welcome-to-blue-river', 'north-america', 'North America', 'Jean drove me north', '2024-02-27', false, 33),
  ('Rest day in Clearwater', 'https://irunearth.substack.com/p/rest-day-in-clearwater', 'north-america', 'North America', 'Newspaper interviews and Hitchcock', '2024-02-26', false, 34),
  ('Welcome to Clearwater', 'https://irunearth.substack.com/p/welcome-to-clearwater', 'north-america', 'North America', 'A trying run and fascinating evening', '2024-02-25', false, 35),
  ('Little Fort', 'https://irunearth.substack.com/p/little-fort', 'north-america', 'North America', 'Trending on the yellowhead highway', '2024-02-24', false, 36),
  ('McLure', 'https://irunearth.substack.com/p/mclure', 'north-america', 'North America', 'Made a new friend on a farm in McLure', '2024-02-23', false, 37),
  ('Rest day in Kamloops and adventure recap', 'https://irunearth.substack.com/p/rest-day-in-kamloops-and-adventure', 'north-america', 'North America', 'Welcome old friends/new readers!', '2024-02-22', false, 38),
  ('Welcome to Kamloops', 'https://irunearth.substack.com/p/welcome-to-kamloops', 'north-america', 'North America', 'I ran to Kamloops and met my hosts Jen and Ivan', '2024-02-21', false, 39),
  ('Savona', 'https://irunearth.substack.com/p/savona', 'north-america', 'North America', 'A long slow slogging slither to Savona', '2024-02-20', false, 40),
  ('Marble Canyon and Cache Creek', 'https://irunearth.substack.com/p/marble-canyon-and-cache-creek', 'north-america', 'North America', 'Desert, ranch lands, and rivers', '2024-02-19', false, 41),
  ('Wendy Thompson and Keith’s hut', 'https://irunearth.substack.com/p/wendy-thompson-and-keiths-hut', 'north-america', 'North America', 'A week running from Pemberton to Lilloet and skiing Duffy Lake Road', '2024-02-17', false, 42),
  ('Wendy Thompson Placeholder', 'https://irunearth.substack.com/p/wendy-thompson-placeholder', 'north-america', 'North America', 'gone camping!', '2024-02-11', false, 43),
  ('I’m the only fucking coward in this town', 'https://irunearth.substack.com/p/im-the-only-fucking-coward-in-this', 'north-america', 'North America', 'Last minute rest day in Pemberton', '2024-02-10', false, 44),
  ('Welcome to pemberton', 'https://irunearth.substack.com/p/welcome-to-pemberton', 'north-america', 'North America', null, '2024-02-09', false, 45),
  ('Whirlwind peak and Cowboy Ridge', 'https://irunearth.substack.com/p/whirlwind-peak-and-cowboy-ridge', 'north-america', 'North America', 'Another big day', '2024-02-08', false, 46),
  ('Welcome to Kee’s and Claire Hut', 'https://irunearth.substack.com/p/welcome-to-kees-and-claire-hut', 'north-america', 'North America', 'The Canadians really know how to do alpine huts', '2024-02-07', false, 47),
  ('Welcome to Whistler pt 2', 'https://irunearth.substack.com/p/welcome-to-whistler-pt-2', 'north-america', 'North America', 'An unexpected stay in Whistler', '2024-02-06', false, 48),
  ('Welcome to whistler', 'https://irunearth.substack.com/p/welcome-to-whistler', 'north-america', 'North America', 'Under the whistletoe', '2024-02-05', false, 49),
  ('Welcome to Squamish', 'https://irunearth.substack.com/p/welcome-to-squamish', 'north-america', 'North America', 'Made it to Squamish!', '2024-02-04', false, 50),
  ('One more day in lions bay', 'https://irunearth.substack.com/p/one-more-day-in-lions-bay', 'north-america', 'North America', 'Three sport day', '2024-02-03', false, 51),
  ('A love story', 'https://irunearth.substack.com/p/a-love-story', 'north-america', 'North America', 'The start of a beautiful friendship', '2024-02-02', false, 52),
  ('Welcome to Lions Bay', 'https://irunearth.substack.com/p/welcome-to-lions-bay', 'north-america', 'North America', 'Goodbye Vancouver, hello lions bay!!', '2024-01-31', false, 53),
  ('Olly Goggins', 'https://irunearth.substack.com/p/olly-goggins', 'north-america', 'North America', 'The unified theory of olly and Goggins', '2024-01-30', false, 54),
  ('Center of the Community', 'https://irunearth.substack.com/p/center-of-the-community', 'north-america', 'North America', 'Community centers are amazing', '2024-01-29', false, 55),
  ('Vancouver Recovery', 'https://irunearth.substack.com/p/vancouver-recovery', 'north-america', 'North America', 'First recovery day in Vancouver', '2024-01-28', false, 56),
  ('Welcome to Canada', 'https://irunearth.substack.com/p/welcome-to-canada', 'north-america', 'North America', 'Crossed the border and made it to the big city, Vancouver', '2024-01-27', false, 57),
  ('Bellingham to Birch Bay', 'https://irunearth.substack.com/p/bellingham-to-birch-bay', 'north-america', 'North America', 'On the road again!!', '2024-01-26', false, 58),
  ('Stay soft', 'https://irunearth.substack.com/p/stay-soft', 'north-america', 'North America', 'Chilling is part of the mission', '2024-01-25', false, 59),
  ('Injury-free or it doesn’t count', 'https://irunearth.substack.com/p/injury-free-or-it-doesnt-count', 'north-america', 'North America', 'Struggling to outrun “no pain no gain”', '2024-01-24', false, 60),
  ('Medically Cleared', 'https://irunearth.substack.com/p/medically-cleared', 'north-america', 'North America', 'A long wait at the medical clinic and time to rethink my stroller to ski strategy', '2024-01-23', false, 61),
  ('Active Recovery', 'https://irunearth.substack.com/p/active-recovery', 'north-america', 'North America', 'Recover now not later!', '2024-01-22', false, 62),
  ('Third times the charm', 'https://irunearth.substack.com/p/third-times-the-charm', 'north-america', 'North America', 'Finally finished my reflections from camping solo in a snow storm (vlog at the bottom)', '2024-01-21', false, 63),
  ('Made it to Bellingham', 'https://irunearth.substack.com/p/made-it-to-bellingham', 'north-america', 'North America', 'I made it to Bham and started adding words to the photos from Mt Baker', '2024-01-20', false, 64),
  ('Back to civilization', 'https://irunearth.substack.com/p/back-to-civilization', 'north-america', 'North America', '“I’m checking in. Everything is okay” - Garmin', '2024-01-19', false, 65),
  ('Gone Skiing Take 2', 'https://irunearth.substack.com/p/gone-skiing-take-2', 'north-america', 'North America', 'Last day in Marblemount. Achilles and Stroller troubleshooting.', '2024-01-14', false, 66),
  ('Invent the day', 'https://irunearth.substack.com/p/invent-the-day', 'north-america', 'North America', 'A morning routine emerges in Marblemount', '2024-01-13', false, 67),
  ('Pay it forward', 'https://irunearth.substack.com/p/pay-it-forward', 'north-america', 'North America', 'The world runs on hitchhikers', '2024-01-12', false, 68),
  ('What storm?', 'https://irunearth.substack.com/p/what-storm', 'north-america', 'North America', 'A beautiful day in Marblemount with new friends', '2024-01-11', false, 69),
  ('Reflections from Limbo', 'https://irunearth.substack.com/p/reflections-from-limbo', 'north-america', 'North America', 'A non-human-powered side trip to Bellingham', '2024-01-10', false, 70),
  ('Saved by the shrimp scampi', 'https://irunearth.substack.com/p/saved-by-the-shrimp-scampi', 'north-america', 'North America', 'Welcoming the start of the snow in newfound community', '2024-01-09', false, 71),
  ('And I’m still here', 'https://irunearth.substack.com/p/and-im-still-here', 'north-america', 'North America', 'Intimations of the boy who cried wolf', '2024-01-08', false, 72),
  ('Gone Skiing', 'https://irunearth.substack.com/p/gone-skiing', 'north-america', 'North America', 'Going skiing! No posts this week', '2024-01-07', false, 73),
  ('Darrington and Marblemount', 'https://irunearth.substack.com/p/darrington-and-marblemount', 'north-america', 'North America', 'First Mon to Fri on the jogger is in the books', '2024-01-06', false, 74),
  ('Granite Falls and Oso', 'https://irunearth.substack.com/p/granite-falls-and-oso', 'north-america', 'North America', 'Oso you think you can dance', '2024-01-04', false, 75),
  ('Snohomish and Lake Stevens', 'https://irunearth.substack.com/p/snohomish-and-lake-stevens', 'north-america', 'North America', 'Welcome to farm country', '2024-01-03', false, 76),
  ('And we’re off', 'https://irunearth.substack.com/p/and-were-off', 'north-america', 'North America', 'A smoooth day 1. Many people to thank.', '2024-01-02', false, 77),
  ('Countdown', 'https://irunearth.substack.com/p/countdown', 'north-america', 'North America', 'Fell asleep writing this post so it got cut short', '2024-01-01', false, 78),
  ('How to Run with the Ugandans Pt. 4', 'https://irunearth.substack.com/p/how-to-run-with-the-ugandans-pt-4', 'africa', 'Africa', null, '2024-11-13', false, 79),
  ('How to Run with the Ugandans Pt. 3', 'https://irunearth.substack.com/p/how-to-run-with-the-ugandans-pt-3', 'africa', 'Africa', null, '2024-11-09', false, 80),
  ('How to Run with the Ugandans Pt. 2', 'https://irunearth.substack.com/p/how-to-run-with-the-ugandans-pt-2-cf8', 'africa', 'Africa', null, '2024-11-08', false, 81),
  ('How to Run with the Ugandans Pt. 1', 'https://irunearth.substack.com/p/how-to-run-with-the-ugandans-pt-1', 'africa', 'Africa', null, '2024-11-07', false, 82),
  ('Chimerica Live Updates: At least 25 Killed, says Health Ministry', 'https://irunearth.substack.com/p/chimerica-live-updates-at-least-25', 'africa', 'Africa', 'At least 25 Rabbitian people were killed in a new wave of attacks on Friday. This brings the overall death toll since Sept 7 to 43,341, the Health Ministry said.', '2024-11-04', false, 83),
  ('Running to Uganda Pt. 2 and Does economic development translate to human development?', 'https://irunearth.substack.com/p/running-to-uganda-pt-2-and-does-economic', 'africa', 'Africa', 'This post completes the tale of my 150km run from the Shoe 4 Africa Children’s Hospital to Uganda. Read about my adventure, a research-based comparison between Kenya an Uganda, and broader conclusions', '2024-10-26', false, 84),
  ('Running to Uganda And The Comparative Challenges Facing Children’s Development in Africa and the West', 'https://irunearth.substack.com/p/running-to-uganda-and-the-comparative', 'africa', 'Africa', null, '2024-10-16', false, 85),
  ('How to Run With the Kenyans Pt. 3', 'https://irunearth.substack.com/p/how-to-run-with-the-kenyans-pt-3', 'africa', 'Africa', 'In the third and final part in my series on running with the Kenyans, I detail some of my experiences living and running with athletes in the legendary town of Iten.', '2024-10-07', false, 86),
  ('How to Run With the Kenyans Pt. 2', 'https://irunearth.substack.com/p/how-to-run-with-the-kenyans-pt-2', 'africa', 'Africa', 'This is part two in a series on my time training with the pros in Iten, in which I diverge from the memoir to research how great Kenyans really are and why they’re so good.', '2024-10-06', false, 87),
  ('Food Aid Update: Feedback from the Widows of Neruo', 'https://irunearth.substack.com/p/food-aid-update-feedback-from-the', 'africa', 'Africa', 'I decided to do something I’ve never done before and publish a guest post, you will see why.', '2024-10-02', false, 88),
  ('How to Run with the Kenyans Pt. 1', 'https://irunearth.substack.com/p/how-to-run-with-the-kenyans-pt-1', 'africa', 'Africa', 'This post details my introduction to running with Kenyan pros and the legendary town of Iten. It probably caters most to the running buffs, but anyone interested in the daily routines of pro athletes.', '2024-09-30', false, 89),
  ('Welcome to East Africa’s only public children’s hospital!!', 'https://irunearth.substack.com/p/welcome-to-east-africas-only-public', 'africa', 'Africa', null, '2024-09-27', false, 90),
  ('Cheplaskei', 'https://irunearth.substack.com/p/cheplaskei', 'africa', 'Africa', null, '2024-09-26', false, 91),
  ('Himaki', 'https://irunearth.substack.com/p/himaki', 'africa', 'Africa', null, '2024-09-25', false, 92),
  ('Kebeneti', 'https://irunearth.substack.com/p/kebeneti', 'africa', 'Africa', null, '2024-09-23', false, 93),
  ('Chepkinoiyo', 'https://irunearth.substack.com/p/chepkinoiyo', 'africa', 'Africa', null, '2024-09-18', false, 94),
  ('Tenduet', 'https://irunearth.substack.com/p/tenduet', 'africa', 'Africa', null, '2024-09-17', false, 95),
  ('Meet The Kalenjins', 'https://irunearth.substack.com/p/meet-the-kalenjins', 'africa', 'Africa', null, '2024-09-16', false, 96),
  ('Narok', 'https://irunearth.substack.com/p/narok', 'africa', 'Africa', null, '2024-09-13', false, 97),
  ('Ewaso Ngiro', 'https://irunearth.substack.com/p/ewaso-ngiro', 'africa', 'Africa', null, '2024-09-11', false, 98),
  ('Narasura', 'https://irunearth.substack.com/p/narasura', 'africa', 'Africa', null, '2024-09-09', false, 99),
  ('Welcome to Kenya', 'https://irunearth.substack.com/p/welcome-to-kenya', 'africa', 'Africa', null, '2024-09-07', false, 100),
  ('Ol Doinyo Lengai', 'https://irunearth.substack.com/p/magadini', 'africa', 'Africa', 'Climbing the “Mountain of God” and the runs leading up to it.', '2024-09-02', false, 101),
  ('Kilimanjaro to Ketumbeine', 'https://irunearth.substack.com/p/kilimanjaro-to-ketumbeine', 'africa', 'Africa', null, '2024-08-31', false, 102),
  ('Olmoloqvety', 'https://irunearth.substack.com/p/olmoloqvety', 'africa', 'Africa', null, '2024-08-27', false, 103),
  ('Kyeeri', 'https://irunearth.substack.com/p/kyeeri', 'africa', 'Africa', null, '2024-08-26', false, 104),
  ('Mt Meru Run Trip Report', 'https://irunearth.substack.com/p/mt-meru-run-trip-report', 'africa', 'Africa', 'On Wednesday, I ran Mt Meru. At 4562m/14968ft, it’s the second highest peak in Tanzania and fifth highest in Africa.', '2024-08-24', false, 105),
  ('Run Update from Mshiri', 'https://irunearth.substack.com/p/run-update-from-mshiri', 'africa', 'Africa', null, '2024-08-20', false, 106),
  ('Ruwu: Lost in the Jungle', 'https://irunearth.substack.com/p/ruwu-lost-in-the-jungle', 'africa', 'Africa', null, '2024-08-20', false, 107),
  ('China Vs USA in Tanzania: Battle on the edges of two empires', 'https://irunearth.substack.com/p/china-vs-usa-in-tanzania-battle-on', 'africa', 'Africa', null, '2024-08-19', false, 108),
  ('Three Entrepreneurs in Moshi, Tanzania', 'https://irunearth.substack.com/p/three-entrepreneurs-in-moshi-tanzania', 'africa', 'Africa', null, '2024-08-17', false, 109),
  ('The Contradiction Inherent to Every NGO According to a Dutchman', 'https://irunearth.substack.com/p/the-contradiction-inherent-to-every', 'africa', 'Africa', null, '2024-08-13', false, 110),
  ('How to do International Food Aid and Succeed as an African Entrepreneur in One Day', 'https://irunearth.substack.com/p/how-to-do-international-food-aid', 'africa', 'Africa', 'We have just delivered 311kg of food to seven families in the village of Neru.', '2024-08-12', false, 111),
  ('Five Widows', 'https://irunearth.substack.com/p/five-widows', 'africa', 'Africa', null, '2024-08-08', false, 112),
  ('Olly and Rocky’s Insider Guide to Your African Safari', 'https://irunearth.substack.com/p/olly-and-rockys-insider-guide-to', 'africa', 'Africa', null, '2024-08-06', false, 113),
  ('Onward (or not!)', 'https://irunearth.substack.com/p/onward-or-not', 'africa', 'Africa', null, '2024-08-02', false, 114),
  ('Mt Kilimanjaro Trip Report', 'https://irunearth.substack.com/p/mt-kilimanjaro-trip-report', 'africa', 'Africa', 'Marangu route from the gate to the top in 24 hours', '2024-07-30', false, 115),
  ('Book Review: The Power of Women', 'https://irunearth.substack.com/p/pre-kilimanjaro-take-2', 'africa', 'Africa', null, '2024-07-27', false, 116),
  ('Kilimanjaro Prep', 'https://irunearth.substack.com/p/kilimanjaro-prep-drama', 'africa', 'Africa', 'Some more insight for my paid subscribers', '2024-07-27', false, 117),
  ('Shimbwe', 'https://irunearth.substack.com/p/shimbwe', 'africa', 'Africa', null, '2024-07-26', false, 118),
  ('Maki High School', 'https://irunearth.substack.com/p/maki-high-school', 'africa', 'Africa', null, '2024-07-25', false, 119),
  ('Neru', 'https://irunearth.substack.com/p/neru', 'africa', 'Africa', null, '2024-07-23', false, 120),
  ('New Beginnings', 'https://irunearth.substack.com/p/new-beginnings', 'africa', 'Africa', 'I get knocked down! I get up again!', '2024-07-23', false, 121),
  ('Let’s talk politics', 'https://irunearth.substack.com/p/lets-talk-politics', 'africa', 'Africa', 'I tried writing about politics in Tanzania several times and always hit a wall.', '2024-07-21', false, 122),
  ('Sidelined', 'https://irunearth.substack.com/p/sidelined', 'africa', 'Africa', null, '2024-07-18', false, 123),
  ('Kilimanjaro Rest Days', 'https://irunearth.substack.com/p/kilimanjaro-rest-days', 'africa', 'Africa', 'Resting before the climb', '2024-07-15', false, 124),
  ('Mbahe', 'https://irunearth.substack.com/p/mbahe', 'africa', 'Africa', 'Day 11', '2024-07-14', false, 125),
  ('Kisangiro', 'https://irunearth.substack.com/p/kisangiro', 'africa', 'Africa', 'Day 10', '2024-07-12', false, 126),
  ('Njoro (Village)', 'https://irunearth.substack.com/p/njoro-village', 'africa', 'Africa', 'Day 9', '2024-07-11', false, 127),
  ('Muungano', 'https://irunearth.substack.com/p/muungano', 'africa', 'Africa', 'Day 8', '2024-07-09', false, 128),
  ('Take me to church', 'https://irunearth.substack.com/p/take-me-to-church', 'africa', 'Africa', 'Day 7', '2024-07-09', false, 129),
  ('Ruvu Jitengeni', 'https://irunearth.substack.com/p/ruvu-jitengeni', 'africa', 'Africa', 'Day 6', '2024-07-07', false, 130),
  ('Hedaru', 'https://irunearth.substack.com/p/hedaru', 'africa', 'Africa', 'Day 5', '2024-07-06', false, 131),
  ('Mkumbara', 'https://irunearth.substack.com/p/mkumbara', 'africa', 'Africa', 'Day 4', '2024-07-05', false, 132),
  ('Kwasunga', 'https://irunearth.substack.com/p/kwasunga', 'africa', 'Africa', 'Day 3', '2024-07-04', false, 133),
  ('Day 2 is in the books', 'https://irunearth.substack.com/p/day-2-is-in-the-books', 'africa', 'Africa', 'I''ll save you the suspense', '2024-07-02', false, 134),
  ('Muheza (The run begins!!)', 'https://irunearth.substack.com/p/muheza-the-run-begins', 'africa', 'Africa', 'A crazy day yes it was', '2024-07-01', false, 135),
  ('Dar es Salaam', 'https://irunearth.substack.com/p/dar-es-salaam', 'africa', 'Africa', 'Ideas about charity and a night out in Tanzania’s biggest city', '2024-06-30', false, 136),
  ('La Banana', 'https://irunearth.substack.com/p/la-banana', 'africa', 'Africa', 'Mzungu kichaa (“crazy white man”)', '2024-06-27', false, 137),
  ('Romantic Intentions', 'https://irunearth.substack.com/p/romantic-intentions', 'africa', 'Africa', 'Ninakupenda (“I love you”)', '2024-06-24', false, 138),
  ('Matemwe', 'https://irunearth.substack.com/p/matemwe', 'africa', 'Africa', 'Nazi tamu (“yummy coconut”)', '2024-06-23', false, 139),
  ('Zanzibar Training Camp', 'https://irunearth.substack.com/p/zanzibar-training-camp', 'africa', 'Africa', 'Mambo jambo jambo', '2024-06-21', false, 140),
  ('Welcome to Kilamajuu', 'https://irunearth.substack.com/p/welcome-to-kilamajuu', 'africa', 'Africa', 'Kila ma who?', '2024-06-20', false, 141),
  ('And then there was one', 'https://irunearth.substack.com/p/and-then-there-was-one', 'africa', 'Africa', 'Family returns to the USA', '2024-06-19', false, 142),
  ('Lake Manyara and Serengeti National Parks', 'https://irunearth.substack.com/p/lake-manyara-and-serengeti-national', 'africa', 'Africa', 'A week in the African bush', '2024-06-17', false, 143),
  ('Morning rush hour', 'https://irunearth.substack.com/p/morning-rush-hour', 'africa', 'Africa', 'A run through town in Arusha', '2024-06-11', false, 144),
  ('Welcome to Tanzania', 'https://irunearth.substack.com/p/welcome-to-tanzania', 'africa', 'Africa', 'Hakuna matata', '2024-06-10', false, 145),
  ('Building a women’s hostel', 'https://irunearth.substack.com/p/building-a-womens-hostel', 'africa', 'Africa', 'No one has ever become poor from giving', '2024-06-08', false, 146),
  ('Slowly then all at once', 'https://irunearth.substack.com/p/slowly-then-all-at-once', 'africa', 'Africa', 'Last night in New York', '2024-06-07', false, 147),
  ('The State of Children''s Health', 'https://irunearth.substack.com/p/the-state-of-childrens-health', 'africa', 'Africa', 'How are the kids doing?', '2024-06-04', false, 148),
  ('The Africa Uniform', 'https://irunearth.substack.com/p/the-africa-uniform', 'africa', 'Africa', 'Thanks to Amundsen and Norda for providing the clothes and shoes to run Africa!!', '2024-06-03', false, 149),
  ('Big Dumb Adventure Housekeeping Updates', 'https://irunearth.substack.com/p/big-dumb-adventure-housekeeping-updates', 'africa', 'Africa', 'The fundraiser is live!', '2024-06-02', false, 150),
  ('Hey Honey', 'https://irunearth.substack.com/p/hey-honey-lets-make-some-money', 'africa', 'Africa', 'Scrambling to figure out my life in New York before flying to Africa', '2024-06-01', false, 151),
  ('Africa Adventure Concept', 'https://irunearth.substack.com/p/africa-adventure-concept', 'africa', 'Africa', 'Running to the man who ran to Kilimanjaro', '2024-05-31', false, 152),
  ('Asia 2025: That''s a Wrap!', 'https://irunearth.substack.com/p/asia-2025-thats-a-wrap', 'asia', 'Asia', 'Thank you', '2025-07-31', false, 153),
  ('Miyako (1000 Miles Asia)', 'https://irunearth.substack.com/p/miyako-1000-miles-asia', 'asia', 'Asia', 'Japan Day 24', '2025-07-29', false, 154),
  ('Kanehama', 'https://irunearth.substack.com/p/kanehama', 'asia', 'Asia', 'Japan Day 23', '2025-07-28', false, 155),
  ('Kirikiri', 'https://irunearth.substack.com/p/kirikiri', 'asia', 'Asia', 'Japan Day 22', '2025-07-27', false, 156),
  ('Kamaishi', 'https://irunearth.substack.com/p/kamaishi', 'asia', 'Asia', 'Japan Day 21', '2025-07-26', false, 157),
  ('Ofunato', 'https://irunearth.substack.com/p/ofunato', 'asia', 'Asia', 'Japan Day 20', '2025-07-25', false, 158),
  ('Rikuzentakata', 'https://irunearth.substack.com/p/rikuzentakata', 'asia', 'Asia', 'Japan Day 19', '2025-07-24', false, 159),
  ('Oshima Island', 'https://irunearth.substack.com/p/oshima-island', 'asia', 'Asia', 'Japan Day 18', '2025-07-23', false, 160),
  ('Okawa Elementary School', 'https://irunearth.substack.com/p/okawa-elementary-school', 'asia', 'Asia', 'Japan Day 17', '2025-07-22', false, 161),
  ('Onagawa', 'https://irunearth.substack.com/p/onagawa', 'asia', 'Asia', 'Japan Day 16', '2025-07-21', false, 162),
  ('Sendai', 'https://irunearth.substack.com/p/sendai', 'asia', 'Asia', 'Japan Day 15', '2025-07-20', false, 163),
  ('Tokyo (Special Post)', 'https://irunearth.substack.com/p/tokyo-special-post', 'asia', 'Asia', 'Japan Day 14', '2025-07-19', false, 164),
  ('Toyama', 'https://irunearth.substack.com/p/toyama', 'asia', 'Asia', 'Japan Day 13', '2025-07-18', false, 165),
  ('Tateyama', 'https://irunearth.substack.com/p/tateyama', 'asia', 'Asia', 'Japan Day 12', '2025-07-17', false, 166),
  ('Yarigatake', 'https://irunearth.substack.com/p/yarigatake', 'asia', 'Asia', 'Japan Day 11', '2025-07-16', false, 167),
  ('Kamicochi', 'https://irunearth.substack.com/p/kamicochi', 'asia', 'Asia', 'Japan Day 10', '2025-07-15', false, 168),
  ('Central Japan Alps Traverse', 'https://irunearth.substack.com/p/central-japan-alps-traverse', 'asia', 'Asia', 'Japan Day 9', '2025-07-14', false, 169),
  ('Senjo', 'https://irunearth.substack.com/p/senjo', 'asia', 'Asia', 'Japan Day 7', '2025-07-13', false, 170),
  ('Shiomi', 'https://irunearth.substack.com/p/shiomi', 'asia', 'Asia', 'Japan Day 6', '2025-07-12', false, 171),
  ('Aikaishi ft. Paul Deckret', 'https://irunearth.substack.com/p/aikaishi-ft-paul-deckret', 'asia', 'Asia', 'Japan day 5', '2025-07-11', false, 172),
  ('Zaru', 'https://irunearth.substack.com/p/zaru', 'asia', 'Asia', 'Japan day 4', '2025-07-10', false, 173),
  ('Hayakawa', 'https://irunearth.substack.com/p/hayakawa', 'asia', 'Asia', 'Japan Day 3', '2025-07-09', false, 174),
  ('Lake Motosu', 'https://irunearth.substack.com/p/lake-motosu', 'asia', 'Asia', 'Japan day 2', '2025-07-08', false, 175),
  ('Mt Fuji Sea to Summit', 'https://irunearth.substack.com/p/mt-fuji-sea-to-summit', 'asia', 'Asia', 'Welcome to Japan!', '2025-07-07', false, 176),
  ('Asia Day 24: Rekong Peo & Intermission', 'https://irunearth.substack.com/p/asia-day-24-rekong-peo-and-intermission', 'asia', 'Asia', null, '2025-06-24', false, 177),
  ('Asia Day 23: Charang La', 'https://irunearth.substack.com/p/asia-day-23-charang-la', 'asia', 'Asia', null, '2025-06-23', false, 178),
  ('Asia Day 21: Rupin Pass', 'https://irunearth.substack.com/p/asia-day-21-rupin-pass', 'asia', 'Asia', null, '2025-06-22', false, 179),
  ('Asia Day 20: Jakha', 'https://irunearth.substack.com/p/asia-day-20-jakha', 'asia', 'Asia', null, '2025-06-21', false, 180),
  ('Asia Day 19: Chanshal Pass', 'https://irunearth.substack.com/p/asia-day-19-chanshal-pass', 'asia', 'Asia', null, '2025-06-20', false, 181),
  ('Asia Day 18: Rorhu', 'https://irunearth.substack.com/p/asia-day-18-rorhu', 'asia', 'Asia', null, '2025-06-19', false, 182),
  ('Asia Day 17: Kaphnu', 'https://irunearth.substack.com/p/asia-day-17-kaphnu', 'asia', 'Asia', null, '2025-06-18', false, 183),
  ('Asia Day 16: Pin Bhaba Pass', 'https://irunearth.substack.com/p/asia-day-16-pin-bhaba-pass', 'asia', 'Asia', null, '2025-06-17', false, 184),
  ('Asia Day 15', 'https://irunearth.substack.com/p/asia-day-15', 'asia', 'Asia', null, '2025-06-16', false, 185),
  ('Asia Day 14', 'https://irunearth.substack.com/p/asia-day-14', 'asia', 'Asia', null, '2025-06-15', false, 186),
  ('Asia Day 13', 'https://irunearth.substack.com/p/asia-day-13', 'asia', 'Asia', null, '2025-06-14', false, 187),
  ('Asia Day 11: Great Himalaya Trail', 'https://irunearth.substack.com/p/asia-day-11-great-himalaya-trail', 'asia', 'Asia', null, '2025-06-13', false, 188),
  ('Asia Day 10: Great Himalayan Trail', 'https://irunearth.substack.com/p/asia-day-10-great-himalayan-trail', 'asia', 'Asia', null, '2025-06-12', false, 189),
  ('Asia Day Nine: Great Himalayan Trail', 'https://irunearth.substack.com/p/asia-day-nine', 'asia', 'Asia', null, '2025-06-11', false, 190),
  ('Asia Day Seven: Great Himalayan Trail', 'https://irunearth.substack.com/p/asia-day-seven-great-himalayan-trail', 'asia', 'Asia', null, '2025-06-10', false, 191),
  ('Asia Day Six: Great Himalaya Trail', 'https://irunearth.substack.com/p/asia-day-six-great-himalaya-trail', 'asia', 'Asia', null, '2025-06-09', false, 192),
  ('Asia Day Five: Great Himalayan Trail', 'https://irunearth.substack.com/p/asia-day-five-great-himalayan-trail', 'asia', 'Asia', null, '2025-06-08', false, 193),
  ('Asia Day Four: Great Himalaya Trail', 'https://irunearth.substack.com/p/asia-day-four-great-himalaya-trail', 'asia', 'Asia', null, '2025-06-07', false, 194),
  ('Asia Day Three: Great Himalaya Trail', 'https://irunearth.substack.com/p/asia-day-three-great-himalaya-trail', 'asia', 'Asia', null, '2025-06-06', false, 195),
  ('Asia Day Two: Great Himalaya Trail', 'https://irunearth.substack.com/p/asia-day-two-great-himalaya-trail', 'asia', 'Asia', null, '2025-06-05', false, 196),
  ('Asia Day One: Great Himalaya Trail', 'https://irunearth.substack.com/p/asia-day-one-great-himalaya-trail', 'asia', 'Asia', null, '2025-06-04', false, 197),
  ('Zanskar', 'https://irunearth.substack.com/p/zanskar', 'asia', 'Asia', null, '2025-05-27', false, 198),
  ('How to go ski mountaineering in India', 'https://irunearth.substack.com/p/how-to-go-ski-mountaineering-in-india', 'asia', 'Asia', null, '2025-05-24', false, 199),
  ('The Himalayan Bootpackers', 'https://irunearth.substack.com/p/the-himalayan-bootpackers', 'asia', 'Asia', 'Sunil and Ankur take Garen, Jess, and I jeep skiing', '2025-05-08', false, 200),
  ('Asia Launch', 'https://irunearth.substack.com/p/asia-launch', 'asia', 'Asia', 'I Run Earth in 2025: Asia Edition', '2025-05-03', false, 201),
  ('What''s a Human For', 'https://irunearth.substack.com/p/whats-a-human-for', 'tech', 'Tech', 'The most important skill for software engineers is setting up feedback loops for AI to build and test integrated components of a system.', '2026-02-01', true, 202),
  ('You''re Fired', 'https://irunearth.substack.com/p/youre-fired', 'tech', 'Tech', 'Today, I''m planning to fire two highly talented Principal Engineers with 10+ years of experience because I think I can do their job with Claude.', '2026-01-01', true, 203),
  ('Millbrook Alumni Summit', 'https://irunearth.substack.com/p/millbrook-alumni-summit', 'personal', 'Personal', 'Our culture raises men to believe their value is tied to money. I crested a hill in the rain, feeling the weight of my soaking backpack, and broke into tears.', '2025-04-15', true, 204),
  ('2025 Rainier Ski Descent', 'https://irunearth.substack.com/p/2025-rainier-ski-descent', 'personal', 'Personal', null, '2025-04-01', false, 205);

-- Clear existing press items and re-seed
DELETE FROM press_items;

INSERT INTO press_items (title, url, source, tag, date, sort_order) VALUES
  ('Ep:55 I Run Earth - Laufend die Welterkunden (Teil 2)', 'https://open.spotify.com/episode/1gSKUh9ZqefWenF9Qetjcq?si=7LdPMADsQ6yCu4GzYMGr-w', 'Bergeistern - der apline Podcast', 'Podcast', 'Mar 2026', 1),
  ('Ep:55 I Run Earth - Laufend die Welterkunden (Teil 1)', 'https://open.spotify.com/episode/3780HFbME9eJJc4Ye73AFf?si=gyIaBzgYQkiQF9HbD2zwmQ', 'Bergeistern - der alpine Podcast', 'Podcast', 'Feb 2026', 2),
  ('Heroes today can often get lost in the sea of media', 'https://www.linkedin.com/posts/toby-tanser_heroes-today-can-often-get-lost-in-the-sea-activity-7245424230710824961-it80?utm_source=share&utm_medium=member_desktop&rcm=ACoAAB0Wg5gBYjC7ocK9PxY0NeSGE2ZQ3WetGTY', 'Toby Tanser', 'Press', 'Oct 2024', 3),
  ('A lovely, delightful traipse', 'https://drive.google.com/file/d/1JjGIvd2zNHAmRUwlCnr_LRKWC5j9Hw7m/view?usp=sharing', 'Ferry County View', 'Press', 'Apr 2024', 4),
  ('Human-powered adventurer comes through Kootenays', 'https://drive.google.com/file/d/1SuEItwAJYjGhlB8IgqG2dovK4pm4im0p/view?usp=sharing', 'The Valley Voice', 'Press', 'Apr 2024', 5),
  ('Ski run for snow', 'https://www.cbc.ca/listen/live-radio/1-52-radio-active/clip/16052448-ski-run-snow', 'CBC Edmonton', 'Press', 'Mar 2024', 6),
  ('A human-powered adventure into the Rockies with Olly', 'https://www.clearwatertimes.com/local-news/a-human-powered-adventure-into-the-rockies-with-olly-7326150', 'Clearwater Times', 'Press', 'Mar 2024', 7),
  ('Seattle to Mount Robson on Foot', 'https://www.therockymountaingoat.com/2024/03/seattle-to-mount-robson-on-foot/', 'The Rocky Mountain Goat', 'Press', 'Mar 2024', 8),
  ('Millbrook School Alumni Summit Speaker', 'https://www.millbrook.org/school-life/academics/alumni-summit/alumni-summit-speakers-2025/oliver-cohen-16', 'Millbrook School', 'Speaking', '2025', 9);

-- Clear existing causes and re-seed
DELETE FROM causes;

INSERT INTO causes (name, adventure_label, description, url, sort_order) VALUES
  ('Give Directly', 'North America 2024', 'Fundraiser for Give Directly. Raised $5,320.', 'https://www.every.org/givedirectly/f/give-directly-to-people', 1),
  ('Shoe 4 Africa', 'Africa 2024', 'Fundraiser for Shoe 4 Africa. Raised $15,865.', 'https://www.every.org/shoe4africa/f/running-to-the-man-who', 2),
  ('Rise Against Hunger', 'Asia 2025', 'Fundraiser for Rise Against Hunger. Raised $3,702.', 'https://www.gofundme.com/f/olly-runs-asia', 3),
  ('Kilimanjaro Aid Project', 'Andes 2026', 'Building chicken coops to provide food and self-sustaining income to underfed families in the foothills of Kilimanjaro.', null, 4);

-- NOTE: Adventures, sponsors, and stats are NOT included here.
-- Those are already seeded correctly in migration.sql.
-- Only run the DELETE+INSERT blocks above for tables with new Webflow data.
