#!/bin/bash
# Materialize .env.local from environment-configured secrets so the Cloudinary
# upload script and Supabase REST helpers in CLAUDE.md work in remote (web)
# sessions. Locally, .env.local already exists — this hook is a no-op there.
#
# Public values (cloud name, project URL) are defaulted below since they're
# already in CLAUDE.md and every delivery URL on the site. Only the three
# actual secrets need to be configured on the Claude Code environment
# (https://code.claude.com/docs/en/claude-code-on-the-web):
#   CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET, SUPABASE_SERVICE_KEY
# Env vars override these defaults if set.
#
# The hook is idempotent and skips silently if none of the secrets are set.

set -euo pipefail

# Only act in Claude Code on the web. Locally the user manages .env.local.
if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  exit 0
fi

ENV_FILE="${CLAUDE_PROJECT_DIR:-$(pwd)}/.env.local"

# Public, non-secret defaults.
CLOUDINARY_CLOUD_NAME="${CLOUDINARY_CLOUD_NAME:-dhrlrjvax}"
SUPABASE_URL="${SUPABASE_URL:-https://upocwcjkyyhufaaalblz.supabase.co}"

# Skip if none of the actual secrets are configured yet — first-time setup
# shouldn't fail before the user has populated the environment.
if [ -z "${CLOUDINARY_API_KEY:-}${CLOUDINARY_API_SECRET:-}${SUPABASE_SERVICE_KEY:-}" ]; then
  echo "session-start: no Cloudinary/Supabase secrets set; skipping .env.local" >&2
  exit 0
fi

umask 077
tmp="$(mktemp "${ENV_FILE}.XXXXXX")"
{
  echo "# Auto-generated by .claude/hooks/session-start.sh — do not edit by hand."
  echo "# Sourced from the Claude Code environment's configured env vars."
  printf 'CLOUDINARY_CLOUD_NAME=%s\n' "$CLOUDINARY_CLOUD_NAME"
  [ -n "${CLOUDINARY_API_KEY:-}" ]    && printf 'CLOUDINARY_API_KEY=%s\n'    "$CLOUDINARY_API_KEY"
  [ -n "${CLOUDINARY_API_SECRET:-}" ] && printf 'CLOUDINARY_API_SECRET=%s\n' "$CLOUDINARY_API_SECRET"
  [ -n "${SUPABASE_SERVICE_KEY:-}" ]  && printf 'SUPABASE_SERVICE_KEY=%s\n'  "$SUPABASE_SERVICE_KEY"
  printf 'SUPABASE_URL=%s\n' "$SUPABASE_URL"
} > "$tmp"

chmod 600 "$tmp"
mv "$tmp" "$ENV_FILE"
echo "session-start: wrote $ENV_FILE" >&2
